### ISSUE TITLE
Unable to access board after upgrade

### ISSUE THREAD

**Issue by scramatte** [professor-jonny/images#1]
Hello,

I've flashed my DR40X9 v04 board with your firmware.

Since upgrade, I'm unable to access board.  Board doesn't answer to ping  neither ssh or http.
I've tried with serial cable  without success.  I've got weird characters when I try to connect probably due to cable or  serial port misconfiguration.

Can you give me an hand?

Regards

**Comment by professor-jonny** [comment]
How did you flash the firmware as the factory qsdk firmware wont let you and you need to do it from uboot with tftp as it wont pass the QSDK image checks.

Settings for the serial are are 115200 8n1
you generally only need to hook up ground and rx and tx  in some cases connecting the 3.3v is not advised.
The pin clostest to the centre going to wards the outside edge is as follows: 
GND RX TX 3.3v

Also remember to swap over the tx and tx from end to end if your serial converter does not do it.

It sounds like you have a corrupt UBI partition and it is in part because the stock uboot is broken and really designed for qsdk firmware.

To be honest sysupgrade some times does not work because uboot is a bit hacky on the board and it really needs to get replaced with a proper implementation, I have talked to wallys about this, it seems that the partition format reverts to 64mb after a sysupgrade and throws error ubi error 22.

It is recomended to flash from uboot using the instructions in my readme sysupgrade likely wont work correctly.

I'm about to update the flash images on the repo as it now has support for the fibreport from backports from master and I have updated  upnp to master so it works  (hopefully)

**Comment by scramatte** [comment]
Hi,

I've been able to get working serial and boot the card using your  README procedure.
I'm impatient to get latest image as I need to test fiber port.

Regards

**Comment by professor-jonny** [comment]
New image is up instructions are in the read me in the code repo.(pasted below)
`
download the firmware from https://github.com/professor-jonny/images/blob/main/wallys2openwrt.img Run the following command on uboot mode
1.  tftpboot 0x84000000 wallys2openwrt.img
2.  imgaddr=0x84000000 && source $imgaddr:script
3.  reset
after above steps , we can run the following command to update openwrt firmware you can find the latest prebuilt firmware on my repo here https://github.com/professor-jonny/images/blob/main/

1.  tftpboot 0x84000000 openwrt-ipq40xx-generic-Wallys_DR4029-squashfs-nand-factory.ubi
2.  nand device 0
3.  nand erase 0x0 0x8000000
4.  nand write 0x84000000 0x0 0x4000000
5.  reset
`
You must follow precisely if you mess up the erase or muck up an address you could potentially kill the board be warned.

**Comment by scramatte** [comment]
Hello,

I need to rebuild images to add support for TR069 / CWMP. Can I reflash it at same hex address ?

regards

**Comment by professor-jonny** [comment]
Yes regardless of the image the factory image flash procedure is the same.
You could likely add that in with opkg from bash or luci. Once proper partition support happens with MIBIB /SMEM corrections then sysupgrades should work. There are others playing with this I believe. You can sysupgrade from intraramfs boot also but it is more of a hassle.

**Comment by scramatte** [comment]
I'm trying to rebuild image, but  it looks that repository doesn't include .config file as by default try to compile for Ath79 platform. Can you send me or commit .config file you use?

**Comment by professor-jonny** [comment]
It is bad to include a .config as different devices have different dependancys, you should copy only the output of scripts/diffconfig.sh as the new .config between devices or platforms you wont find a . config on any openwrt source code repo or git for that reason.

I can send you the config file but you need to use the diff script and pach the config you initally created by just an open select platform and save, you would then need to fix conflicts by running a test make.

If you had a later update of the feeds it could render a broken image by using my confi directly, for example luci recently defaults to wolfssl it could render luci inoperable by loading an older config on newer feeds that defaults to open_ssl libs.

You are best to create your own and add in what you want, you can see a list of the packages I have included in the zip file on the images,
I could recompile with support for tr069 if you wish but you need to then include keys/ server details etc to make it usefull for you or it would revert on doing a hardware reset.

My image is bleeding edge (master) you might be best to build from stable and add in the wallys patches your self on a current stable version.

If you are doing some cloud platform remote managment of multiple devices you probally want to look at securing a vpn and seperate custom images per device with keys included, creating yur own .config  then really makes sence.
you could us the auto builder for this to some what automate creation of hunderds of devices.

**Comment by scramatte** [comment]
I'm quite new with the process.  Currently I've got DR4029  and I talk with Wallys and send me  their own repository https://github.com/Wallystech/openwrt  but I haven't check it yet.

Are you able to make us a reference  .config for DR4029 ?  We can discuss about it in private.

About TR069 we have seen EasyCWMP and other  project called ICWMP that looks more complete.
I was unable to build EasyCWMP with Openwrt 19.x   , I haven't tried yet ICWMP...

**Comment by professor-jonny** [comment]
No fibre with wallys repo, dts and drivers are not there, only works on qsdk firmware except it is patched in here recently from up stream patches.
I'll make you a config and put in the image repo.

**Comment by scramatte** [comment]
Thank you very much

**Comment by professor-jonny** [comment]
Here you go:
https://github.com/professor-jonny/images/blob/main/config_sample

I had to rename it because of the project setup you just need to greate a base config by first updating and installing the feeds and then running  `make menuconfig` and saving  a config file then you just have to run the diff script and apply it to the config to set all the stock options.
I'm guessing you will create your own network, dhcp, wireless configs etc... otherwise you can pull them from the running image and place them in the files folder.

**Comment by scramatte** [comment]
Thank you,  just one thing, I don't how to use the diff_script ...
As I haven't any config yet , I understand that can copy your example and rename it .config

**Comment by professor-jonny** [comment]
As i understand you use the make defconfig to create a config.seed and use that to create a .config file you could use a visual tool like win merge to view the differences between my file. And a .config you create by selecting the same platform and target and try to select the same packages best you can.

The .config file is created automatically by the make menuconfig procedure normally dependancys can change so it is dangerous to hand edit.
So best to use the script or a visual tool to see differences and only change them.
 Then you can then use ? From the makemenu interface to check dependancys after that they are all satisfied.

https://openwrt.org/docs/guide-developer/build-system/use-buildsystem
